// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7n4cb7ELkzPHrtPxWTr7QqDm5FElzE8U',
    appId: '1:102278939910:web:241a97f993c927d46b0a87',
    messagingSenderId: '102278939910',
    projectId: 'hive-app-d73d8',
    authDomain: 'hive-app-d73d8.firebaseapp.com',
    storageBucket: 'hive-app-d73d8.firebasestorage.app',
    measurementId: 'G-SHS6BEFX62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4pMcjMjowOB3ywG_72XXN3o8Seea0Is',
    appId: '1:102278939910:android:5e1ee77a14cfd7fd6b0a87',
    messagingSenderId: '102278939910',
    projectId: 'hive-app-d73d8',
    storageBucket: 'hive-app-d73d8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7n4cb7ELkzPHrtPxWTr7QqDm5FElzE8U',
    appId: '1:102278939910:web:5fbc4fe3499b799b6b0a87',
    messagingSenderId: '102278939910',
    projectId: 'hive-app-d73d8',
    authDomain: 'hive-app-d73d8.firebaseapp.com',
    storageBucket: 'hive-app-d73d8.firebasestorage.app',
    measurementId: 'G-0N573H019E',
  );
}
